kind: pipeline
type: docker
name: Staging

steps:
  - name: build
    image: node
    commands:
      - yarn install

  - name: Test application with maven
    image: maven:3.6.3-adoptopenjdk-11
    commands:
      - mvn test -B

  - name: Build image
    image: docker:20.10.0-dind
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - cd /drone/src/
      - docker build -t easycook:latest .

  - name: Create service
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker-compose -f /drone/src/docker-compose.yml -p backend-easycook down
      - docker-compose -f /drone/src/docker-compose.yml -p backend-easycook up -d

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
  event:
    - push
