kind: pipeline
type: docker
name: Staging

steps:
#  - name: Test application with maven
#    image: maven:3.6.3-adoptopenjdk-11
#    commands:
#      - mvn test -B

  - name: Build image
    image: docker:20.10.0-dind
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - cd /drone/src/
      - docker build -t easycook .

  - name: Create service
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      #把原本的container 關掉
      - docker-compose -f /drone/src/docker-compose.yml -p backend down
      #重新開啟現在的container
      - docker-compose -f /drone/src/docker-compose.yml -p backend up -d
      # docker rmi 表示移除images $(特定ID), docker images -f "dangling=true" -q 會show出所有tag=<none>的無用images, -q表示顯示 id
      - docker rmi $(docker images -f "dangling=true" -q)

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - master
  event:
    - push
