
# h2 if you want to use in-memories
#spring:82:mem:easyCook

# Data Source Setup
# Note: Users must create a mysql db that they will reference here, create a user that has access to it on localhost
#       and provide the credentials below to access it //http://140.118.110.164/
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
#    url: jdbc:mysql://localhost:3306/easyCook?serverTimezone=UTC
    url: jdbc:mysql://140.118.9.145:3306/easycook?serverTimezone=UTC
    username: shannon
    password: hung0602
    initialization-mode: always
    data:
      - classpath:/db/dev/employeelist.sql
      - classpath:/db/dev/ingredient.sql
      - classpath:/db/dev/memberlist.sql
      - classpath:/db/product/recipe.sql
      - classpath:/db/product/recipe_ingredient.sql
      - classpath:/db/product/recipe_step.sql
  jpa:
    # uncomment the below lines to view sql output in console
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate.ddl-auto: create-drop

# Server port is arbitrary
server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# JWT
security:
  jwt:
    secret: ThisIsEasyCookSecretKeyCreatedByShannon
  account:
    admin:
      username: admin
      password: a19519b15b5ae2ddb93f7c67881ab3ea14a38cb9c5912f4f4362840b97894bf3
